quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000
%dev.quarkus.http.cors.origins=/.*/

# Configuracion de JWT
mp.jwt.verify.issuer=https://fullstack.app/issuer
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
quarkus.smallrye-jwt.enabled=true

# Configuración de Base de Datos H2
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb

# Generar y actualizar las tablas automáticamente según las entidades Java
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
